name: Deployment

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: Prod
    steps:
      - uses: actions/checkout@v3
      - name: Run the deployment script
        run: |
          ./deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          APP_DOMAIN_NAME: ${{ vars.APP_DOMAIN_NAME }}
          CDN_DOMAIN_NAME: ${{ vars.CDN_DOMAIN_NAME }}
          COGNITO_DOMAIN_NAME: ${{ vars.COGNITO_DOMAIN_NAME }}
          DOMAIN: ${{ vars.DOMAIN }}
          STAGE: ${{ vars.STAGE }}
          FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
          HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
